/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ACol: typeof import('ant-design-vue/es')['Col']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    ARow: typeof import('ant-design-vue/es')['Row']
    copy: typeof import('./src/components/VariableArea copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    PromptArea: typeof import('./src/components/PromptArea.vue')['default']
    ResultArea: typeof import('./src/components/ResultArea.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunArea: typeof import('./src/components/RunArea.vue')['default']
    RunningArea: typeof import('./src/components/RunningArea.vue')['default']
    RunningItem: typeof import('./src/components/RunningItem.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    VariableArea: typeof import('./src/components/VariableArea.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
    WorkshopArea: typeof import('./src/components/WorkshopArea.vue')['default']
  }
}
